### ISSUE TITLE
Some programming logic issues

### ISSUE THREAD

**Issue by kalsmic** [bekeplar/iReporter#22]
Why did you create two validation functions and not one instead?
https://github.com/bekeplar/iReporter/blob/887c8a7fb6cc39170330e9606b0fb19810ab66a9/api/validator.py#L26-L52
What's the essence of validate_input and validate_inputs? Why not have one continuous function?

https://github.com/bekeplar/iReporter/blob/887c8a7fb6cc39170330e9606b0fb19810ab66a9/api/Helpers.py#L17-L21
What does this function do? I do not understand the logic. ` if user.username == None:`

If your target is to avoid adding a duplicate user then you would loop through a list of user objects while comparing the username or email or both and if there is a match then user already exists.

**Comment by bekeplar** [comment]
I

**Comment by bekeplar** [comment]
I have fixed that bro thanks ...still on string and integer validation

**Comment by kalsmic** [comment]
- Balance the tests.
 I noticed that in one place you test for only status codes and in another only the data, both are equally important.
**_For example, what status code does the user receive for the following scenario_**
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/tests/test_user.py#L26-L49
- Validate the data before creating the object
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L40-L46
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L120-L124
- This function does not do anything other than simply looping through the list of users. Please take note that Line 13 will never run unless there exists a user object with username set to none
.
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/Helpers.py#L9-L13
This also means that this next piece of code also does not do anything.
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L58
You can generate the password hash at the time of creating the user object.

- Your login function should also  verify the password of the user.
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/Helpers.py#L16-L21
replace your if statement condition at https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/Helpers.py#L19 with https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L87

- I think 401 would be a more appropriate status code for this error
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L95-L98
- Not a correct status code, you can either use 406 or 409 refer to this [list of HTTP status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L128-L131
- Revisit the rubric, return an empty list if user does not have any records.
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/views.py#L149-L154
- Consider reducing the complexity of this function.
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/validator.py#L6-L22
You can use the same approach you used for 
https://github.com/bekeplar/iReporter/blob/25da141ba33d31d164827e6c7e93d3639763a7cd/api/validator.py#L26-L38
**Conclusion.**
- Please work on the status codes and the authentication logic

**Comment by bekeplar** [comment]
Thanks man for these wonderful observations
